INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Bernard', 'Toxic effect of lacrimogenic gas, intentional self-harm', '72920 Buena Creek Rd     Gaskil', ' OK');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Bautista', 'Drug or chemical induced diabetes mellitus with hyperosmolarity', '18572 W Truckhaven Trail     Willow Run', ' ME');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Beard', 'Poisoning by unspecified drugs primarily affecting the autonomic nervous system, accidental (unintentional)', '22670 Lost Creek Rd     Hebron', ' RI');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Reyes', 'Puncture wound of abdominal wall without foreign body, left upper quadrant without penetration into peritoneal cavity', '23501 Cardinal Way      Willaha', ' TX');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Sullivan', 'Carcinoma in situ of eye', '20716 Beach Club Rd     Sacramento', ' IN');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Wilkins', 'Stress fracture, left shoulder', '46941 Birdsell Rd      Center', ' AZ');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Zuniga', 'Cerebral infarction due to thrombosis of precerebral arteries', '89548 Calinda Dr      Bent Pine', ' OK');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Ruiz', 'Other specified injury of left Achilles tendon', '11817 Pine Hills Rd     Farmington Lake', ' MS');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Dumas', 'Fracture of lower end of humerus', '37670 Melinda De Oro     Pickerel Narrows', ' AZ');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Russell', 'Chronic gout due to renal impairment, left hip', '78564 Otay Truck Trail     Cimarron', ' AZ');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Mcconnell', 'Paving stone degeneration of retina', '71357 Valle Vista Rd     Morgan Mill', ' OK');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Mcknight', 'Poisoning by, adverse effect of and underdosing of methylphenidate', '31640 Sawday Rd      East Natchitoches', ' KS');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Petty', 'Benign neoplasm of ureter', '9123 Jewel Valley Rd     Rabbitown', ' AL');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Ryan', 'Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy with macular edema', '34743 Akuunyaa Way      Brentwood Village', ' FL');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Walsh', 'Nondisplaced fracture of lateral condyle of right femur', '4318 Scott Ln      Stanardsville', ' WV');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Park', 'Infection following other infusion, transfusion and therapeutic injection', '67442 E Plaza Blvd     Pickerel Narrows', ' AZ');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Payne', 'Syphilis complicating pregnancy, childbirth and the puerperium', '13071 Hwy 67      Spring City', ' WA');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Christian', 'Triplet pregnancy with two or more monochorionic fetuses', '31879 Blockton Dr      Scottsville', ' FL');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Fisher', 'Motorcycle rider (driver) (passenger) injured in other specified transport accidents', '47242 Barona Rd      Lyon', ' AL');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Nielsen', 'Laceration of intrinsic muscle and tendon at ankle and foot level, left foot', '68513 Windy Mountain Ln     East Waterford', ' MS');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Branch', 'Injury of conjunctiva and corneal abrasion without foreign body, right eye', '48026 Breezy Ln      Fairland', ' TN');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Mcclure', 'Toxic effect of nitroglycerin and other nitric acids and esters, assault', '6715 Thing Valley Rd     Warner', ' ME');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Escobar', 'Unspecified injury of deep palmar arch of left hand', '25348 El Mirlo      Stanardsville', ' OK');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Livingston', 'Pathological fracture in neoplastic disease, hand', '50212 Hwy 78      Morgan Mill', ' AZ');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Valenzuela', 'Direct infection of ankle and foot in infectious and parasitic diseases classified elsewhere', '17780 Paima Ln      Bent Pine', ' WA');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Roach', 'Driver of pick-up truck or van injured in collision with other and unspecified motor vehicles in nontraffic accident', '29852 Calnino Tres Ave     Brookhaven', ' MT');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Holden', 'Inhalant dependence with intoxication', '55509 Cherimoya Dr      Momford Landing', ' IL');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Austin', 'Other serum reaction due to vaccination', '75856 Mountain Vista Rd     Mount Baker', ' NY');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Bolton', 'Pathological dislocation of ankle and foot, not elsewhere classified', '78818 Hubbard Rd      Wilhelm Park', ' MT');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Harmon', 'Periprosthetic osteolysis of internal prosthetic joint', '63469 Springview Rd      Ipswich', ' FL');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Mooney', 'Underdosing of unspecified systemic antibiotic', '56043 Castle Creek Way     Brookhaven', ' OH');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Reynolds', 'Salter-Harris Type I physeal fracture of lower end of left tibia', '60206 Chaisson Rd      Storms', ' OK');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Peck', 'Unspecified injury of right thigh', '97969 Middle Peak Loop Fire Rd   North Knoxville', ' VA');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Duarte', 'Acute sinusitis, unspecified', '75968 Panoramic Pl      Conyersville', ' OK');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Greer', 'Open bite of right great toe with damage to nail', '98631 Camp De Luz Rd    Mitchell', ' NM');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Simon', 'Poisoning by alpha-adrenoreceptor antagonists, intentional self-harm', '47089 Reservoir Rd      Longview', ' NH');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Andersen', 'Injury of right internal carotid artery, intracranial portion, not elsewhere classified with loss of consciousness of 6 hours to 24 hours', '43596 Mollusk Wash      Midland City', ' AL');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Brennan', 'Adverse effect of ophthalmological drugs and preparations', '37546 Butterfield Ranch Trailer Park    Coal Creek', ' MT');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Hurley', 'Corrosion of first degree of right elbow', '77301 Cll Rociada      North Knoxville', ' SD');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Goodman', 'Mechanical ectropion of eyelid', '49705 Seven Bridges Rd     East Waterford', ' GA');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Vaughn', 'Poisoning by other antihypertensive drugs, accidental (unintentional)', '12932 Arredondo St      Emerson', ' NJ');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Krueger', 'Unspecified injury at T1 level of thoracic spinal cord', '87200 Romo Rd      Momford Landing', ' AK');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Mitchell', 'Fall from, out of or through building or structure', '95795 Akuunyaa Way      Cimarron', ' NY');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Crane', 'Streptococcus, Staphylococcus, and Enterococcus as the cause of diseases classified elsewhere', '59664 Ave B      Cimarron', ' VA');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Clayton', 'Persistent migraine aura without cerebral infarction, not intractable', '86805 Valleyview Dr      Pickerel Narrows', ' MT');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Dawson', 'Intracranial and intraspinal abscess and granuloma', '18186 Gentle Oaks Trail     Merrimac South', ' DE');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Miranda', 'Superficial frostbite of wrist', '10847 Jamacha Blvd      Center', ' OK');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Velez', 'Pedal cycle passenger injured in collision with heavy transport vehicle or bus in traffic accident', '77486 Rag Doll Ln     Hebron', ' MT');
INSERT INTO DOCTOR (LAST_NAME, VISIT_INFO, ADDRESS, STATE) VALUES ('Krause', 'Burn of second degree of unspecified forearm', '35212 Meadowlark Dr      Fairland', ' DC');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Paul', 'Luna', 'M', '1978-03-28', '72', '288');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Sienna', 'Saunders', 'F', '1988-03-28', '71', '301');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Joel', 'Carson', 'F', '1978-03-28', '60', '329');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Kimberly', 'Lang', 'F', '1978-03-28', '77', '279');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Toby', 'Steele', 'F', '1978-03-28', '73', '215');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Valerie', 'Rosales', 'F', '1978-03-28', '70', '307');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Jaylon', 'Berg', 'M', '1978-03-28', '81', '307');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Javon', 'Mckenzie', 'M', '1978-03-28', '61', '179');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Oswaldo', 'Ingram', 'F', '1978-03-28', '64', '224');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Adriel', 'Rosario', 'F', '1978-03-28', '67', '281');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Naomi', 'Jessie', 'F', '1978-03-28', '75', '161');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Will', 'Beard', 'M', '1978-03-28', '71', '160');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Eddie', 'Bruce', 'F', '1978-03-28', '74', '179');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Jimmy', 'Vargas', 'F', '1978-03-28', '74', '169');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Nina', 'Carey', 'F', '1978-03-28', '72', '183');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Myah', 'Summers', 'F', '1978-03-28', '77', '160');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Emmalee', 'Rivera', 'F', '1978-03-28', '60', '334');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Cooper', 'Duke', 'F', '1978-03-28', '68', '130');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Alexandra', 'Valencia', 'F', '1978-01-05', '70', '322');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Maeve', 'Elliott', 'F', '1978-01-05', '69', '233');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, SEX, DOB, HEIGHT, WEIGHT) VALUES ('Jabari', 'Bolton', 'M', '1978-01-05', '63', '140');


INSERT INTO DOCTOR_VISIT (DOCTOR_ID, USER_ID, VISIT_DATE) VALUES ((SELECT DOCTOR_ID FROM DOCTOR WHERE LAST_NAME = 'Bernard'), (SELECT USER_ID FROM USERS WHERE LAST_NAME = 'Luna'), '1978-01-05');